# Jacobi Iterative Method 

$$Ax=b$$
$$(D + (A-D)) x=b$$
$$ \text { with } D \text { diagonal matrix with diagonal values of } A$$
so
$$Dx + (A-D)x=b$$
then
$$x = D^{-1}(D-A)x+ D^{-1}b $$
if 
$$ B = D^{-1}(D-A)$$
and
$$ c = D^{-1}b$$
we have
$$x = Bx+ c $$

## Jacobi iteration
$$x^{(0)} $$
$$x^{(k+1)} = Bx^{(k)}+ c $$

Loosely speaking, Jacobi iteration converges well if $A$ is “close” to a diagonal matrix. 

In [260]:
import numpy as np
from scipy.linalg import inv, solve, det, eig

# A   “close” to a diagonal matrix.
n = 4
Aux =  np.diag(np.arange(1,n+1))
A = Aux + np.random.random((n, n)) # Loosely speaking, Jacobi iteration converges well if A is “close” to a diagonal matrix.
b=  A@(2*np.ones(n)) # x = [2, ... , 2]
print("A= ", A)
print("b= ", b)
print("det(A)= ", det(A))
print("solve(A,b)= ", solve(A,b))

A=  [[1.33869225 0.78114139 0.49110745 0.40124915]
 [0.39034339 2.20054868 0.62622662 0.47465376]
 [0.70543429 0.65869964 3.25824237 0.23398006]
 [0.78862556 0.12872735 0.37654187 4.21717342]]
b=  [ 6.02438049  7.38354491  9.7127127  11.02213641]
det(A)=  31.373703707935263
solve(A,b)=  [2. 2. 2. 2.]


In [261]:
D = np.diag(np.diag(A))
D

array([[1.33869225, 0.        , 0.        , 0.        ],
       [0.        , 2.20054868, 0.        , 0.        ],
       [0.        , 0.        , 3.25824237, 0.        ],
       [0.        , 0.        , 0.        , 4.21717342]])

In [262]:
B = inv(D)@(D-A)
print("B= ", B)
print("eig(B)= ", eig(B))

B=  [[ 0.         -0.58351081 -0.36685613 -0.29973218]
 [-0.17738457  0.         -0.28457749 -0.21569791]
 [-0.21650762 -0.2021641   0.         -0.07181174]
 [-0.18700335 -0.03052456 -0.08928774  0.        ]]
eig(B)=  (array([-0.67326394+0.j        ,  0.30017065+0.09945961j,
        0.30017065-0.09945961j,  0.07292263+0.j        ]), array([[ 0.74100466+0.j        ,  0.72258179+0.j        ,
         0.72258179-0.j        , -0.02971718+0.j        ],
       [ 0.45628368+0.j        ,  0.01128927-0.36335328j,
         0.01128927+0.36335328j, -0.04531645+0.j        ],
       [ 0.40519327+0.j        , -0.3341283 +0.34441116j,
        -0.3341283 -0.34441116j, -0.58384946+0.j        ],
       [ 0.28024225+0.j        , -0.33666136+0.04605284j,
        -0.33666136-0.04605284j,  0.8100513 +0.j        ]]))


In [263]:
c = inv(D)@b
print("c= ", c)

c=  [4.50019824 3.35531996 2.98096692 2.61363129]


In [264]:
x = np.zeros(n)
steps = 30
for k in range(steps):
  print(k,x)
  x = B@x+c

0 [0. 0. 0. 0.]
1 [4.50019824 3.35531996 2.98096692 2.61363129]
2 [0.66535739 1.14498331 1.14062507 1.40349569]
3 [2.99296998 2.60996851 2.50464998 2.35241329]
4 [1.35331324 1.60423561 1.63639329 1.75063321]
5 [2.4390674  2.27197444 2.23792943 2.16547875]
6 [1.7044148  1.81871344 1.83807178 1.88834684]
7 [2.19865307 2.12259673 2.10866409 2.07526732]
8 [1.86603936 1.91760365 1.92680036 1.94940663]
9 [2.09009736 2.05550641 2.04929428 2.03410203]
10 [1.93930603 1.96263434 1.96682291 1.97705581]
11 [2.0408516  2.02515664 2.02234237 2.01545285]
12 [1.97249268 1.98306227 1.98495985 1.98959782]
13 [2.01851879 2.01140319 2.01012674 2.00700388]
14 [1.98753177 1.99232249 1.99318227 1.99528465]
15 [2.00839438 2.00516894 2.0045902  2.00317469]
16 [1.99434837 1.99651992 1.9969096  1.99786259]
17 [2.00380504 2.002343   2.00208066 2.00143904]
18 [1.9974382  1.99842254 1.99859917 1.99903115]
19 [2.00172477 2.00106205 2.00094313 2.00065229]
20 [1.99883878 1.99928496 1.99936502 1.99956083]
21 [2.0007818

# Jacobi iteration, convergence

Loosely speaking, Jacobi iteration converges well to the solution of $Ax=b$ if  $A$  is “close” to a diagonal matrix.

If  $A$  is “close” to a diagonal matrix then
$$\|B \| < 1$$
interpreted loosely as
$$\|B \| = \max_{1⩽j⩽m} |\lambda_j|$$
with 
$$\lambda_1,\lambda_1,\cdots,\lambda_m$$ 
the eigenvalues of $B$.

The convergence is linear

$$\left\|x^{(k)} -L \right\| \le \|B\| \left\|x^{(k-1)} -L\right\|$$

and

$$\left\|x^{(k)} -L \right\| \le \|B\|^k \left\|x^{(0)} -L\right\|$$

In [305]:
import numpy as np
from scipy.linalg import inv, solve, det, eig

n = 3
Aux =  np.diag(np.arange(1,n+1))
A = Aux + np.random.random((n, n)) # Loosely speaking, Jacobi iteration converges well if A is “close” to a diagonal matrix.
b=  A@(2*np.ones(n)) # x = [2, ... , 2]

print("A= ", A)
print()
print("b= ", b)
print()
print("det(A)= ", det(A))
print()
print("solve(A,b)= ", solve(A,b))
print()

D = np.diag(np.diag(A))
B = inv(D)@(D-A)
c = inv(D)@b


L = 2*np.ones(n)

x = np.zeros(n)
print("  k                   x^(k)                     error_k= norm(x^(k)-L) " ) 
for k in range(10):
  print(format(k, '3'),"  ", format(str(x),'35'),"  ",format(np.linalg.norm(x-L), '.17f'))
  x = B@x+c

print()
l,v = eig(B)
print("Max abs eigenvale of B ",np.max(np.abs(l)))
print()


x = np.zeros(n)
C = 0
k_ant = 0
k_steps = 0
print("  k                   x^(k)                     error_n= norm(x^(k)-L)       k_steps      C      " ) 
print(format(0, '3'),"  ", format(str(x),'35'),"  ",format(np.linalg.norm(x-L), '.17f'),format(n_steps, '10'),format(C, '10')) 
for k in range(0,100):
  x = B@x+c
  if (np.linalg.norm(x-L) < 0.5 * 10**(-C)): 
    while (np.linalg.norm(x-L) < 0.5 * 10**(-C)): 
       C =C+1
    k_steps = k- k_ant
    k_ant = k
    print(format(k, '3'),"  ", format(str(x),'35'),"  ",format(np.linalg.norm(x-L), '.17f'),format(k_steps, '10'),format(C, '10')) 

A=  [[1.06449314 0.78101345 0.37216926]
 [0.15054323 2.60338776 0.92628219]
 [0.92127506 0.96862273 3.59578795]]

b=  [ 4.43535172  7.36042634 10.97137149]

det(A)=  8.415235221397312

solve(A,b)=  [2. 2. 2.]

  k                   x^(k)                     error_k= norm(x^(k)-L) 
  0    [0. 0. 0.]                             3.46410161513775439
  1    [4.16663249 2.82724935 3.0511731 ]     2.54629196037393424
  2    [1.02553887 1.50070643 1.22204617]     1.34316072317347945
  3    [2.63831834 2.33314411 2.38416443]     0.81609902542791968
  4    [1.62126179 1.82640343 1.7467154 ]     0.48757716338102897
  5    [2.2159206  2.11201923 2.14379926]     0.28257431013611045
  6    [1.86753678 1.9363506  1.91450368]     0.17002168113418201
  7    [2.07659058 2.03807929 2.05108402]     0.09962793909866249
  8    [1.95420136 1.97739545 1.97011908]     0.05917221434985616
  9    [2.02703185 2.01327994 2.0178232 ]     0.03499634436214814

Max abs eigenvale of B  0.591683619135544

  k           

# Divergent cases

## No solvable det(A) = 0 

In [311]:
import numpy as np
from scipy.linalg import inv, solve, det, eig

A = np.arange(1,n**2+1).reshape(n,n)
#A = Aux + np.random.random((n, n)) # A   “far” to a diagonal matrix.
b=  A@(2*np.ones(n)) # x = [2, ... , 2]

print("A= ", A)
print()
print("b= ", b)
print()
print("det(A)= ", det(A))
print()


D = np.diag(np.diag(A))
B = inv(D)@(D-A)
c = inv(D)@b


L = 2*np.ones(n)

x = np.zeros(n)
print("  k                   x^(k)                                              error_k= norm(x^(k)-L) " ) 
for k in range(20):
  print(format(k, '3'),"  ", format(str(x),'65'),"  ",format(np.linalg.norm(x-L), '.17f'))
  x = B@x+c

print()
l,v = eig(B)
print("Max abs eigenvale of B ",np.max(np.abs(l)))
print()

print("solve(A,b)= ")
print( solve(A,b))


A=  [[1 2 3]
 [4 5 6]
 [7 8 9]]

b=  [12. 30. 48.]

det(A)=  0.0

  k                   x^(k)                                              error_k= norm(x^(k)-L) 
  0    [0. 0. 0.]                                                           3.46410161513775439
  1    [12.          6.          5.33333333]                                11.27435635019184268
  2    [-16.         -10.          -9.33333333]                             24.42221211201893993
  3    [60.         30.         26.66666667]                                68.96698082738176083
  4    [-128.  -74.  -68.]                                                  166.06023003717658071
  5    [364.         190.         170.66666667]                             441.40281426883137783
  6    [-880.         -490.         -446.66666667]                          1105.11980245481890961
  7    [2332.         1246.         1125.33333333]                          2870.24629218082554871
  8    [-5856. -3210. -2916.]                           

LinAlgError: ignored

## Solvable det(A) != 0 but Jacobi divergent 

In [313]:
import numpy as np
from scipy.linalg import inv, solve, det, eig

Aux = np.arange(1,n**2+1).reshape(n,n)
A = Aux + np.random.random((n, n)) # A   “far” to a diagonal matrix.
b=  A@(2*np.ones(n)) # x = [2, ... , 2]

print("A= ", A)
print()
print("b= ", b)
print()
print("det(A)= ", det(A))
print()


D = np.diag(np.diag(A))
B = inv(D)@(D-A)
c = inv(D)@b


L = 2*np.ones(n)

x = np.zeros(n)
print("  k                   x^(k)                                              error_k= norm(x^(k)-L) " ) 
for k in range(20):
  print(format(k, '3'),"  ", format(str(x),'65'),"  ",format(np.linalg.norm(x-L), '.17f'))
  x = B@x+c

print()
l,v = eig(B)
print("Max abs eigenvale of B ",np.max(np.abs(l)))
print()

print("solve(A,b)= ")
print( solve(A,b))



A=  [[1.86379716 2.06832066 3.21885007]
 [4.57438552 5.46908096 6.50936408]
 [7.38090995 8.46084457 9.73370457]]

b=  [14.30193579 33.10566114 51.15091817]

det(A)=  -1.5058501989208568

  k                   x^(k)                                              error_k= norm(x^(k)-L) 
  0    [0. 0. 0.]                                                           3.46410161513775439
  1    [7.67354736 6.05324027 5.25503089]                                   7.69500633363450959
  2    [-8.11958673 -6.61957875 -5.82536367]                                15.42528735783968763
  3    [25.08015387 19.77794713 17.16592922]                                32.84439550285304676
  4    [-43.92095617 -35.35510189 -30.95446072]                             67.75053013455031703
  5    [100.36789172  79.63145998  69.29135334]                             142.23576180029130001
  6    [-200.36511683 -160.36669086 -140.07049927]                          295.80163889007667422
  7    [427.54524436 340.35386197 296