# Matrix SymPy

In [1]:
from sympy import Matrix

In [2]:
A = Matrix([[1,2,3],[4,5,6,],[10,11,9]])
A

Matrix([
[ 1,  2, 3],
[ 4,  5, 6],
[10, 11, 9]])

In [3]:
A.LUdecomposition()

(Matrix([
 [ 1, 0, 0],
 [ 4, 1, 0],
 [10, 3, 1]]), Matrix([
 [1,  2,  3],
 [0, -3, -6],
 [0,  0, -3]]), [])

# Matrix.LUdecomposition() init_printing SymPy

In [4]:
import numpy as np
from sympy import Matrix,N,init_printing, eye
init_printing()

In [5]:
A = Matrix([[-2,2,-1], [6,-6,7], [3,-8,4]])
A

⎡-2  2   -1⎤
⎢          ⎥
⎢6   -6  7 ⎥
⎢          ⎥
⎣3   -8  4 ⎦

In [6]:
A.LUdecomposition()

⎛⎡ 1    0  0⎤  ⎡-2  2   -1 ⎤          ⎞
⎜⎢          ⎥  ⎢           ⎥          ⎟
⎜⎢-3/2  1  0⎥, ⎢0   -5  5/2⎥, [[1, 2]]⎟
⎜⎢          ⎥  ⎢           ⎥          ⎟
⎝⎣ -3   0  1⎦  ⎣0   0    4 ⎦          ⎠

In [7]:
A.LUdecomposition?

In [8]:
L, U, perm = A.LUdecomposition()

In [9]:
L*U

⎡-2  2   -1⎤
⎢          ⎥
⎢3   -8  4 ⎥
⎢          ⎥
⎣6   -6  7 ⎦

In [10]:
A

⎡-2  2   -1⎤
⎢          ⎥
⎢6   -6  7 ⎥
⎢          ⎥
⎣3   -8  4 ⎦

In [11]:
(L*U).permuteBkwd(perm)

⎡-2  2   -1⎤
⎢          ⎥
⎢6   -6  7 ⎥
⎢          ⎥
⎣3   -8  4 ⎦

In [12]:
P = eye(A.shape[0]).permuteFwd(perm)
P

⎡1  0  0⎤
⎢       ⎥
⎢0  0  1⎥
⎢       ⎥
⎣0  1  0⎦

# Matrix.QRdecomposition() SymPy

In [13]:
A = Matrix([[1,3], [1,-1]])
A.QRdecomposition()

⎛⎡√2   √2 ⎤            ⎞
⎜⎢──   ── ⎥            ⎟
⎜⎢2    2  ⎥  ⎡√2   √2 ⎤⎟
⎜⎢        ⎥, ⎢        ⎥⎟
⎜⎢√2  -√2 ⎥  ⎣0   2⋅√2⎦⎟
⎜⎢──  ────⎥            ⎟
⎝⎣2    2  ⎦            ⎠

In [14]:
A.eigenvals()

In [15]:
A = Matrix([[1,3], [1,-1]])
Q,R = A.QRdecomposition()
A = R@Q
A

⎡2  0 ⎤
⎢     ⎥
⎣2  -2⎦

In [16]:
Q,R = A.QRdecomposition()
A = R@Q
A

⎡1  3 ⎤
⎢     ⎥
⎣1  -1⎦

In [17]:
A = Matrix([[1,2], [1,-2]])
A

⎡1  2 ⎤
⎢     ⎥
⎣1  -2⎦

In [18]:
A.eigenvals()

In [19]:
N(Matrix([[k  for  k in  A.eigenvals().keys()]]))

[-2.56155281280883  1.56155281280883]

In [20]:
A = Matrix([[1,2], [1,-2]])
for i in range(100):
  Q,R = A.QRdecomposition()
  A = R@Q
A

⎡-4974229448808325459968828135626852121750597217400025650114509787279158864992
⎢─────────────────────────────────────────────────────────────────────────────
⎢ 1941880496835789510894280532642958462778746081087212182357311529443158618547
⎢                                                                             
⎢            803469022129495137770981046170581301261101496891396417650688     
⎢ ────────────────────────────────────────────────────────────────────────────
⎣ 1941880496835789510894280532642958462778746081087212182357311529443158618547

13609   1941880496835789510902315222864253414156455891548917995369922544412072
──────  ──────────────────────────────────────────────────────────────────────
45701   1941880496835789510894280532642958462778746081087212182357311529443158
                                                                              
        3032348951972535949074547602983893658971851136312813467757198257836000
─────   ───────────────────────────────────────────

In [21]:
np.round(np.array(N(A)).astype(np.float64),5)

array([[-2.56155,  1.     ],
       [ 0.     ,  1.56155]])

In [22]:
# https://opencurve.info/real-eigenvalues-and-eigenvectors-of-3x3-matrices-example-3/

A = Matrix([[5,2,0], [2,5,0],[-3,4,6]])
A

⎡5   2  0⎤
⎢        ⎥
⎢2   5  0⎥
⎢        ⎥
⎣-3  4  6⎦

In [23]:
V=A.eigenvals()
V

In [24]:
A = np.array([[5,2,0], [2,5,0],[-3,4,6]])
for i in range(100):
  Q,R = np.linalg.qr(A)
  A = R@Q
A.round(5)

array([[ 7.     , -0.70711, -2.85774],
       [ 0.     ,  6.     , -4.04145],
       [-0.     ,  0.     ,  3.     ]])

In [25]:
A = Matrix([[5,2,0], [2,5,0],[-3,4,6]])
for i in range(4):
  Q,R = A.QRdecomposition()
  A = R@Q
A

⎡                                                                             
⎢                                                                             
⎢                                                                             
⎢                                                                             
⎢                                                                             
⎢                                                                             
⎢                                                                             
⎢                                                                             
⎢                                                                             
⎢                                                                             
⎢                                                             ⎛  1818233579444
⎢                                     111132⋅√129338932618419⋅⎜- ─────────────
⎢                                                   

In [26]:
np.round(np.array(N(A)).astype(np.float64),5)


array([[ 6.57221,  0.19433,  2.14645],
       [ 0.83577,  6.62223, -4.32667],
       [-0.08234,  0.10289,  2.80556]])

In [27]:
A = Matrix([[2,-2,-12], [4,2,-18], [-4,-8,30]])
A

⎡2   -2  -12⎤
⎢           ⎥
⎢4   2   -18⎥
⎢           ⎥
⎣-4  -8  30 ⎦

In [28]:
A.QRdecomposition()

⎛⎡1/3   -2/3  -2/3⎤  ⎡6  6  -36⎤⎞
⎜⎢                ⎥  ⎢         ⎥⎟
⎜⎢2/3   -1/3  2/3 ⎥, ⎢0  6  -6 ⎥⎟
⎜⎢                ⎥  ⎢         ⎥⎟
⎝⎣-2/3  -2/3  1/3 ⎦  ⎣0  0   6 ⎦⎠

In [29]:
Q,R = A.QRdecomposition()

In [30]:
from sympy import latex
print(latex(Q))

\left[\begin{matrix}\frac{1}{3} & - \frac{2}{3} & - \frac{2}{3}\\\frac{2}{3} & - \frac{1}{3} & \frac{2}{3}\\- \frac{2}{3} & - \frac{2}{3} & \frac{1}{3}\end{matrix}\right]


$$\left[\begin{matrix}\frac{1}{3} & - \frac{2}{3} & - \frac{2}{3}\\\frac{2}{3} & - \frac{1}{3} & \frac{2}{3}\\- \frac{2}{3} & - \frac{2}{3} & \frac{1}{3}\end{matrix}\right]$$

In [31]:
# Q is ortonormal rows

Q.transpose()@Q

⎡1  0  0⎤
⎢       ⎥
⎢0  1  0⎥
⎢       ⎥
⎣0  0  1⎦

In [32]:
# Q is ortonormal columns

Q@Q.transpose()

⎡1  0  0⎤
⎢       ⎥
⎢0  1  0⎥
⎢       ⎥
⎣0  0  1⎦

# Jacobi Iterations with SymPy

In [33]:
import numpy as np
from sympy import Matrix, Rational, ones, N

# A   “close” to a diagonal matrix.
n = 4
A =  Matrix(np.diag(np.arange(1,n+1)))
A

⎡1  0  0  0⎤
⎢          ⎥
⎢0  2  0  0⎥
⎢          ⎥
⎢0  0  3  0⎥
⎢          ⎥
⎣0  0  0  4⎦

In [34]:
P = Matrix(np.random.randint(1,10,size =(n,n)))
P

⎡1  7  8  2⎤
⎢          ⎥
⎢3  3  4  5⎥
⎢          ⎥
⎢3  8  9  1⎥
⎢          ⎥
⎣5  9  4  3⎦

In [35]:
for i in range(n):
  for j in range(n):
      A[i,j] = A[i,j] + Rational(1,P[i,j])
A


⎡ 2   1/7  1/8   1/2 ⎤
⎢                    ⎥
⎢1/3  7/3  1/4   1/5 ⎥
⎢                    ⎥
⎢1/3  1/8  28/9   1  ⎥
⎢                    ⎥
⎣1/5  1/9  1/4   13/3⎦

In [36]:
x_sol= Matrix(2*ones(n,1)) 
x_sol

⎡2⎤
⎢ ⎥
⎢2⎥
⎢ ⎥
⎢2⎥
⎢ ⎥
⎣2⎦

In [37]:
b= A*x_sol
b

⎡155⎤
⎢───⎥
⎢ 28⎥
⎢   ⎥
⎢187⎥
⎢───⎥
⎢ 30⎥
⎢   ⎥
⎢329⎥
⎢───⎥
⎢ 36⎥
⎢   ⎥
⎢881⎥
⎢───⎥
⎣ 90⎦

In [38]:
D = Matrix(np.diag(np.diag(A)))
D

⎡2   0    0     0  ⎤
⎢                  ⎥
⎢0  7/3   0     0  ⎥
⎢                  ⎥
⎢0   0   28/9   0  ⎥
⎢                  ⎥
⎣0   0    0    13/3⎦

In [39]:
D.inv()

⎡1/2   0    0     0  ⎤
⎢                    ⎥
⎢ 0   3/7   0     0  ⎥
⎢                    ⎥
⎢ 0    0   9/28   0  ⎥
⎢                    ⎥
⎣ 0    0    0    3/13⎦

In [40]:
D-A

⎡ 0    -1/7  -1/8  -1/2⎤
⎢                      ⎥
⎢-1/3   0    -1/4  -1/5⎥
⎢                      ⎥
⎢-1/3  -1/8   0     -1 ⎥
⎢                      ⎥
⎣-1/5  -1/9  -1/4   0  ⎦

In [41]:
B = D.inv()@(D-A)
B

⎡  0    -1/14   -1/16  -1/4 ⎤
⎢                           ⎥
⎢-1/7     0     -3/28  -3/35⎥
⎢                           ⎥
⎢-3/28  -9/224    0    -9/28⎥
⎢                           ⎥
⎣-3/65  -1/39   -3/52    0  ⎦

In [42]:
c = D.inv()*b
c

⎡155⎤
⎢───⎥
⎢ 56⎥
⎢   ⎥
⎢187⎥
⎢───⎥
⎢ 70⎥
⎢   ⎥
⎢47 ⎥
⎢── ⎥
⎢16 ⎥
⎢   ⎥
⎢881⎥
⎢───⎥
⎣390⎦

In [43]:
x = 0*ones(n,1)
x

⎡0⎤
⎢ ⎥
⎢0⎥
⎢ ⎥
⎢0⎥
⎢ ⎥
⎣0⎦

In [44]:
x = 0*ones(n,1)
steps = 1
for k in range(steps):
  x = B@x+c
x

⎡155⎤
⎢───⎥
⎢ 56⎥
⎢   ⎥
⎢187⎥
⎢───⎥
⎢ 70⎥
⎢   ⎥
⎢47 ⎥
⎢── ⎥
⎢16 ⎥
⎢   ⎥
⎢881⎥
⎢───⎥
⎣390⎦

In [45]:
N(x)

⎡2.76785714285714⎤
⎢                ⎥
⎢2.67142857142857⎥
⎢                ⎥
⎢     2.9375     ⎥
⎢                ⎥
⎣2.25897435897436⎦

In [46]:
x = 0*ones(n,1)
steps = 2
for k in range(steps):
  x = B@x+c
x

⎡894631 ⎤
⎢────── ⎥
⎢489216 ⎥
⎢       ⎥
⎢1801601⎥
⎢───────⎥
⎢1019200⎥
⎢       ⎥
⎢368443 ⎥
⎢────── ⎥
⎢203840 ⎥
⎢       ⎥
⎢ 33079 ⎥
⎢ ───── ⎥
⎣ 17472 ⎦

In [47]:
N(x)

⎡1.82870347658294⎤
⎢                ⎥
⎢1.76766189167975⎥
⎢                ⎥
⎢1.80751079277865⎥
⎢                ⎥
⎣1.89325778388278⎦

In [48]:
x = 0*ones(n,1)
steps = 3
for k in range(steps):
  x = B@x+c
x

⎡703843961⎤
⎢─────────⎥
⎢342451200⎥
⎢         ⎥
⎢ 1352843 ⎥
⎢ ─────── ⎥
⎢  658560 ⎥
⎢         ⎥
⎢470755841⎥
⎢─────────⎥
⎢228300800⎥
⎢         ⎥
⎢26830023 ⎥
⎢──────── ⎥
⎣13249600 ⎦

In [49]:
N(x)

⎡2.05531170864637⎤
⎢                ⎥
⎢2.05424410835763⎥
⎢                ⎥
⎢2.06199821025594⎥
⎢                ⎥
⎣2.02496852735177⎦

In [50]:
x = 0*ones(n,1)
steps = 10
for k in range(steps):
  x = B@x+c
x

⎡6081201220915666781480550215167⎤
⎢───────────────────────────────⎥
⎢3040610534000015060238336000000⎥
⎢                               ⎥
⎢7601498725650676305688237184087⎥
⎢───────────────────────────────⎥
⎢3800763167500018825297920000000⎥
⎢                               ⎥
⎢ 72395220458354497558210230733 ⎥
⎢ ───────────────────────────── ⎥
⎢ 36197744452381131669504000000 ⎥
⎢                               ⎥
⎢3257791615351057132457186377337⎥
⎢───────────────────────────────⎥
⎣1628898500357150925127680000000⎦

In [51]:
N(x)

⎡1.99999347266474⎤
⎢                ⎥
⎢1.99999273584063⎥
⎢                ⎥
⎢1.99999258389129⎥
⎢                ⎥
⎣1.99999669386199⎦

In [52]:
x = 0*ones(n,1)
steps = 25
for k in range(steps):
  x = B@x+c
x

⎡1613428422202804322173583758445020890550650799556598906948112546316979515927 
⎢──────────────────────────────────────────────────────────────────────────── 
⎢806714211101390772158836324839222284418837154325771279400960000000000000000  
⎢                                                                             
⎢12100713166521051526470328380905016467608289706407313720026279380566117934217
⎢─────────────────────────────────────────────────────────────────────────────
⎢ 6050356583260430791191272436294167133141278657443284595507200000000000000000
⎢                                                                             
⎢ 921959098401604235702205010318131043211523492535072036031955216673032063869 
⎢ ─────────────────────────────────────────────────────────────────────────── 
⎢ 460979549200794726947906471336698448239335516757583588229120000000000000000 
⎢                                                                             
⎢674182590706167105915351459676323147593119085502270

In [53]:
N(x)

⎡2.00000000000003⎤
⎢                ⎥
⎢2.00000000000003⎥
⎢                ⎥
⎢2.00000000000003⎥
⎢                ⎥
⎣2.00000000000001⎦

In [54]:
x = 0*ones(n,1)
steps = 30
for k in range(steps):
  x = B@x+c
x

⎡10541772874787734842071225577541199803408189227334306422342395125758692914815
⎢─────────────────────────────────────────────────────────────────────────────
⎢52708864373938675422625007592825648130912086029321458061702376695770644480000
⎢                                                                             
⎢26354432186969337037373432520697664328867581178893251046344526029014089906405
⎢─────────────────────────────────────────────────────────────────────────────
⎢13177216093484668855656251898206412032728021507330364515425594173942661120000
⎢                                                                             
⎢ 8784810728989779007647637212913588394323860440144137714971448617570760325540
⎢ ────────────────────────────────────────────────────────────────────────────
⎢ 4392405364494889618552083966068804010909340502443454838475198057980887040000
⎢                                                                             
⎢ 12549729612842541621190524192934482357677553655223

In [55]:
N(x)

⎡2.0⎤
⎢   ⎥
⎢2.0⎥
⎢   ⎥
⎢2.0⎥
⎢   ⎥
⎣2.0⎦

In [56]:
x = 0*ones(n,1)
steps = 1000
for k in range(steps):
  x = B@x+c
x

⎡47006908766293167017072970307296953156226530419761868434981264072391183091689
⎢─────────────────────────────────────────────────────────────────────────────
⎢23503454383146583508536485153648476578113265209880934217490632036195591545844
⎢                                                                             
⎢58758635957866458771341212884121191445283163024702335543726580090488978864611
⎢─────────────────────────────────────────────────────────────────────────────
⎢29379317978933229385670606442060595722641581512351167771863290045244489432305
⎢                                                                             
⎢ 2798030283707926608159105375434342449775388715462015978272694290023284707838
⎢ ────────────────────────────────────────────────────────────────────────────
⎢ 1399015141853963304079552687717171224887694357731007989136347145011642353919
⎢                                                                             
⎢251822725533713394734319483789090820479784984391581

In [57]:
N(x)

⎡2.0⎤
⎢   ⎥
⎢2.0⎥
⎢   ⎥
⎢2.0⎥
⎢   ⎥
⎣2.0⎦