Solving Triangular Systems 

http://homepages.math.uic.edu/~jan/mcs572/pipetriangular.pdf



Newton polynomial 
$$
P_3(x) = a_0+ a_1 (x-x_0) + a_2(x-x_0)(x-x_1)+ a_3(x-x_0)(x-x_1)(x-x_2)$$

that interpolates the points 
$$
\begin{array} {l}
(x_0,y_0)=(-1,1)\\
(x_1,y_1)=(0,1)\\
(x_2,y_2)=(1,2)\\
(x_3,y_3)=(2,0)
\end{array}$$

Replacing the polynomial expresion in $x_0,x_1$ and $x_2$
 we have 
 $$
\begin{array} {llll}
P_3(x_0)= a_0&  &  & & =y_0 \\
P_3(x_1)= a_0&+a_1 (x_1-x_0)  &  & & =y_1 \\
P_3(x_2)= a_0&+a_1 (x_2-x_0)  &+ a_2(x_2-x_0)(x_2-x_1)  & & =y_2 \\
P_3(x_3)= a_0&+a_1 (x_3-x_0)  &+ a_2(x_3-x_0)(x_3-x_1)  &+a_3(x_3-x_0)(x_3-x_1)(x_3-x_2) & =y_3\\
\end{array}
$$
In matrix form is the following linear system of equations 

$$
X = 
\left[
\begin{array}{ccccc}
1 & 0 & 0  & 0\\
1 & (x_1-x_0)  & 0  & 0 \\
1 & (x_2-x_0) & (x_2-x_0)(x_2-x_1)  & 0\\
1 & (x_3-x_0) &(x_3-x_0)(x_3-x_1) & (x_3-x_0)(x_3-x_1)(x_3-x_2) 
\end{array}
\right]
\left(
\begin{array}{r}
a_0 \\
a_1 \\
a_2
\end{array}
\right)
= 
\left(
\begin{array}{r}
y_0 \\
y_1 \\
y_2
\end{array}
\right)
$$

$$
X = 
\left[
\begin{array}{ccccc}
1 & 0 & 0  & 0\\
\frac{1}{(x_1-x_0)} & 1 & 0  & 0 \\
\frac{1}{ (x_2-x_0)(x_2-x_1)}  & \frac{(x_2-x_0)}{ (x_2-x_0)(x_2-x_1) } & 1  & 0\\
\frac{1}{(x_3-x_0)(x_3-x_1)(x_3-x_2)} & \frac{(x_3-x_0)}{(x_3-x_0)(x_3-x_1)(x_3-x_2) } & \frac{(x_3-x_0)(x_3-x_1)}{(x_3-x_0)(x_3-x_1)(x_3-x_2)}& 1
\end{array}
\right]
\left(
\begin{array}{r}
a_0 \\
a_1 \\
a_2
\end{array}
\right)
= 
\left(
\begin{array}{r}
y_0 \\
\frac{y_1}{(x_1-x_0)} \\
\frac{y_2}{ (x_2-x_0)(x_2-x_1)} 
\end{array}
\right)
$$

Given a lower triangular system (Solving Triangular Systems  http://homepages.math.uic.edu/~jan/mcs572/pipetriangular.pdf )

$$
\left[
\begin{array}{ccccc}
1 & 0 & 0 & \cdots &0 \\
ℓ_{21} &1& 0  &\cdots &0 \\
\vdots & \vdots & \vdots &\ddots & \vdots\\
ℓ_{n1}&ℓ_{n2}&ℓ_{n3}&\cdots & 1
\end{array}
\right]
\left(
\begin{array}{r}
x_1 \\
x_2 \\
\vdots\\
x_n
\end{array}
\right)
=
\left(
\begin{array}{r}
b_1 \\
b_2 \\
\vdots\\
b_n
\end{array}
\right)
$$

The system has solution 

$$
\left\{
\begin{array}{l}
y_1 = b_1 \\
y_2 = b_2 − ℓ_{2,1}y_1\\
y_3 = b_3 − ℓ_{3,1}y_1 − ℓ_{3,2}y_2 \\
\vdots\\
y_n = b_n − ℓ_{n,1}y_1 − ℓ_{n,2}y_2 − · · · − ℓ_{n,n−1}y_{n−1}
\end{array}
\right.
$$



For $k = 1, 2,... , n:$

$$
y_k = b_k − \sum_{i=1}^{k−1} ℓ_{k,i}\ y_i
$$

As an algorithm:

for $k$ from $1$ to $n$ do

$\qquad$$y_k$ := $b_k$

$\qquad$for $i$ from $1$ to $k−1$ do

$\qquad\qquad$$y_k$ := $y_k$ − $ℓ_{k,i}$ ⋆ $y_i$


We count
1 + 2 + · · · + n − 1 =
n(n − 1)
2
multiplications and subtractions.

In the case of Newton polynomials
$$ℓ_{i,j} =
\left\{
\begin{array}{lll}
\frac{(x_i-x_0)(x_i-x_1)\ldots (x_i-x_{i-1}) (x_i-x_{i-1}) \ldots (x_i-x_{j-1})}{(x_i-x_0)(x_i-x_1)\ldots (x_i-x_{i-1}) (x_i-x_{i-1}) \ldots (x_i-x_n)} & for & i < j \\
1  & for & i = j \\
0 & otherwise
\end{array}
\right.
  $$


In [ ]:
import numpy as np

x = np.array([-1, 0, 1, 2]) # x coordinates in space
y = np.array([1, 1, 2, 0]) # f(x)
n = len(x)
pyramid = np.zeros([n, n])
for j in range(1,n):
        for i in range(n-j):
            # create pyramid by updating other columns
            pyramid[i][j] = (pyramid[i+1][j-1] - pyramid[i][j-1]) / (x[i+j] - x[i])
pyramid

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
x = np.array([-1, 0, 1, 2]) # x coordinates in space
y = np.array([1, 1, 2, 0]) # f(x)



4

Newton’s Divided Difference Method for Polynomial Interpolation

https://medium.com/@sddkal/newtons-divided-difference-method-for-polynomial-interpolation-4bc094ba90d7

In [1]:
import numpy as np

x = np.array([-1, 0, 1, 2]) # x coordinates in space
y = np.array([1, 1, 2, 0]) # f(x)

def getNDDCoeffs(x, y):
    """ Creates NDD pyramid and extracts coeffs """
    n = np.shape(y)[0]
    pyramid = np.zeros([n, n]) # Create a square matrix to hold pyramid
    pyramid[::,0] = y # first column is y
    for j in range(1,n):
        for i in range(n-j):
            # create pyramid by updating other columns
            pyramid[i][j] = (pyramid[i+1][j-1] - pyramid[i][j-1]) / (x[i+j] - x[i])
    print(pyramid)
    return pyramid[0] # return first row

coeff_vector = getNDDCoeffs(x, y)
print(coeff_vector)

[[ 1.          0.          0.5        -0.66666667]
 [ 1.          1.         -1.5         0.        ]
 [ 2.         -2.          0.          0.        ]
 [ 0.          0.          0.          0.        ]]
[ 1.          0.          0.5        -0.66666667]


Math 452, Numerical Methods: Polynomial Interpolation Python Programs

http://math.oit.edu/~paulr/Upper/Math_45x/Math_452/interpolation.pdf